export const BANK_LIST_REQUEST = 'BANK_LIST_REQUEST'
export const BANK_LIST_SUCCESS = 'BANK_LIST_SUCCESS'
export const BANK_LIST_FAIL = 'BANK_LIST_FAIL'

export const BANK_DETAILS_REQUEST = 'BANK_DETAILS_REQUEST'
export const BANK_DETAILS_SUCCESS = 'BANK_DETAILS_SUCCESS'
export const BANK_DETAILS_FAIL = 'BANK_DETAILS_FAIL'

export const BANK_DELETE_REQUEST = 'BANK_DELETE_REQUEST'
export const BANK_DELETE_SUCCESS = 'BANK_DELETE_SUCCESS'
export const BANK_DELETE_FAIL = 'BANK_DELETE_FAIL'

export const BANK_CREATE_REQUEST = 'BANK_CREATE_REQUEST'
export const BANK_CREATE_SUCCESS = 'BANK_CREATE_SUCCESS'
export const BANK_CREATE_FAIL = 'BANK_CREATE_FAIL'
export const BANK_CREATE_RESET = 'BANK_CREATE_RESET'

export const BANK_UPDATE_REQUEST = 'BANK_UPDATE_REQUEST'
export const BANK_UPDATE_SUCCESS = 'BANK_UPDATE_SUCCESS'
export const BANK_UPDATE_FAIL = 'BANK_UPDATE_FAIL'
export const BANK_UPDATE_RESET = 'BANK_UPDATE_RESET'

export const BANK_CREATE_REVIEW_REQUEST = 'BANK_CREATE_REVIEW_REQUEST'
export const BANK_CREATE_REVIEW_SUCCESS = 'BANK_CREATE_REVIEW_SUCCESS'
export const BANK_CREATE_REVIEW_FAIL = 'BANK_CREATE_REVIEW_FAIL'
export const BANK_CREATE_REVIEW_RESET = 'BANK_CREATE_REVIEW_RESET'

export const BANK_TOP_REQUEST = 'BANK_TOP_REQUEST'
export const BANK_TOP_SUCCESS = 'BANK_TOP_SUCCESS'
export const BANK_TOP_FAIL = 'BANK_TOP_FAIL'
